'use strict';
const $=x=>document.getElementById(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}),df=new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1});
const n=x=>x==null||!Number.isFinite(x)?'—':nf.format(x),money=x=>x==null||!Number.isFinite(x)?'—':`${nf.format(x/100)} ₽`,pct=x=>x==null||!Number.isFinite(x)?'—':`${df.format(x*100)}%`,date=x=>x?x.slice(0,10).split('-').reverse().join('.'):'—';
const kinds={ad:'Реклама',promotion:'Акция',discount:'Скидка',bundle:'Пакет',bonus:'Бонус',warmup:'Прогрев / гайд',launch:'Запуск',hackathon:'Мероприятие',open_week:'Открытая неделя',unknown:'Без типа'};
const basis={bot_start:'Запуск бота',invite_link:'Именная инвайт-ссылка',tracked_click:'Подтверждённый клик',manual_source:'Со слов пользователя',calendar_price_match:'Совпадение даты, товара и цены',unknown:'Источник неизвестен'};
const tabs=[['overview','Обзор','Экономика рекламы'],['placements','Размещения','Эффективность размещений'],['growth','Рост каналов','Аудитория и отток'],['events','История событий','Завершённые активности'],['funnel','Воронка','От касания до оплаты'],['forecast','Прогноз и факт','Прогноз vs факт'],['cohorts','Когорты','Что происходит после входа'],['ml','ML-сценарии','Вероятность покупки и цена рекламы']];
let D=null,meta=null,tab='overview',mode='clean',busy=false;
let M=null,mlBusy=false,customerResult=null,channelResult=null,mlError='';
let mlForm={course_id:'',as_of:'',discount_pct:20,discount_days:14,contacts:2,channel_id:'',incrementality:'',required_roi:30,quoted_price:'',expected_views:''};
const badge=(s,type='')=>`<span class="badge ${type}">${esc(s)}</span>`;
const pair=(c,m,f=money)=>`<span class="blue">${f(c)}</span> <span class="muted">/</span> <span class="amber">${f(m)}</span>`;
const card=(label,value,sub='')=>`<div class="card"><div class="label">${label}</div><div class="value">${value}</div><div class="sub">${sub}</div></div>`;
const empty=s=>`<div class="empty">${esc(s)}</div>`;
const panel=(title,body,extra='')=>`<div class="panel"><div class="panel-head"><h2>${title}</h2>${extra}</div>${body}</div>`;
function table(cols,rows){if(!rows.length)return empty('Нет записей за выбранный период.');return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr>${cols.map(c=>`<td${c[3]?' class="num"':''}>${c[2]?c[2](r[c[1]],r,i):esc(r[c[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function lineChart(rows,series,{format=money,band=null,markers=false,height=225}={}){
 if(!rows.length)return empty('Пока нет данных для графика.');
 const W=760,H=height,L=72,R=18,T=18,B=35,iw=W-L-R,ih=H-T-B;
 let vals=series.flatMap(s=>rows.map(r=>r[s.key])).filter(x=>x!=null&&Number.isFinite(x));
 if(band)vals.push(...rows.flatMap(r=>[r[band[0]],r[band[1]]]).filter(x=>x!=null));
 if(!vals.length)return empty('Недостаточно подтверждённых данных для расчёта.');
 let lo=Math.min(0,...vals),hi=Math.max(0,...vals);if(hi===lo)hi=lo+1;hi+=.08*(hi-lo);
 const X=i=>L+(rows.length<2?iw/2:i*iw/(rows.length-1)),Y=y=>T+ih-(y-lo)/(hi-lo)*ih;
 let s=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(series.map(x=>x.name).join(', '))}">`;
 for(let j=0;j<5;j++){let v=lo+(hi-lo)*j/4,y=Y(v);s+=`<line x1="${L}" x2="${W-R}" y1="${y}" y2="${y}" stroke="#e5ebf4"/><text x="${L-9}" y="${y+4}" text-anchor="end">${esc(format(v).replace(' ₽',''))}</text>`;}
 if(band){let rs=rows.map((r,i)=>({...r,i})).filter(r=>r[band[0]]!=null&&r[band[1]]!=null);if(rs.length)s+=`<polygon points="${rs.map(r=>`${X(r.i)},${Y(r[band[0]])}`).concat([...rs].reverse().map(r=>`${X(r.i)},${Y(r[band[1]])}`)).join(' ')}" fill="#dce7ff" opacity=".8"/>`;}
 for(const item of series){let path='',pen=false;rows.forEach((r,i)=>{let y=r[item.key];if(y==null){pen=false;return;}path+=`${pen?'L':'M'}${X(i).toFixed(2)} ${Y(y).toFixed(2)} `;pen=true;});s+=`<path d="${path}" stroke="${item.color}" fill="none" stroke-width="2.5"${item.dashed?' stroke-dasharray="7 5"':''}/>`;if(rows.length<15)rows.forEach((r,i)=>{if(r[item.key]!=null)s+=`<circle cx="${X(i)}" cy="${Y(r[item.key])}" r="3" fill="${item.color}"><title>${esc(r.day)} · ${esc(item.name)}: ${esc(format(r[item.key]))}</title></circle>`;});}
 const step=Math.max(1,Math.ceil((rows.length-1)/5));rows.forEach((r,i)=>{if(i%step===0||i===rows.length-1)s+=`<text x="${X(i)}" y="${H-9}" text-anchor="middle">${esc(typeof r.day==='number'?r.day+' д':r.day.slice(5).split('-').reverse().join('.'))}</text>`;
 if(markers&&r.markers?.length)s+=`<line x1="${X(i)}" x2="${X(i)}" y1="${T}" y2="${T+ih}" stroke="#bbc8de" stroke-dasharray="3 5"/><circle cx="${X(i)}" cy="${T+3}" r="4" fill="#566c98"><title>${esc(r.markers.map(x=>`${x.id}: ${kinds[x.kind]||x.kind}`).join(', '))}</title></circle>`;});
 return s+'</svg>'+`<div class="legend">${series.map(x=>`<span><i class="legend-dot" style="background:${x.color}"></i>${esc(x.name)}</span>`).join('')}${band?'<span>Заливка — номинальный интервал 80%</span>':''}</div>`;
}
function quality(){let q=D.quality;$('quality').innerHTML=`<div class="quality-row"><b>Качество данных</b><span>Clean: <b>${pct(q.clean_pct)}</b></span><span>Только mixed: <b>${pct(q.mixed_only_pct)}</b></span><span>Без источника: <b>${pct(q.unknown_pct)}</b></span><span>Стоимость размещений известна: <b>${pct(q.known_cost_pct)}</b></span></div><div class="quality-note">Доли по числу оплат, без возвратов. ${q.commerce_complete?'Покрытие оплат подтверждено.':'Полнота сбора оплат за весь период не подтверждена.'} ${q.membership_complete?'Покрытие подписок подтверждено.':'Список подписчиков и удержание могут быть неполными.'} Ошибок: ${q.failed_updates+q.failed_imports+q.failed_replies}. ${q.unmapped_events} входов без определённого источника.</div>`;}
function sources(){let rows=D.sources.sort((a,b)=>b.mixed_minor-a.mixed_minor),max=Math.max(1,...rows.map(r=>r.mixed_minor));return rows.map(r=>`<div class="source"><div class="source-label"><b>${esc(r.source)}</b>${pair(r.clean_minor,r.mixed_minor)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(0,r.clean_minor)/max*100}%"></div></div><div class="bar-track"><div class="bar-fill mix" style="width:${Math.max(0,r.mixed_minor)/max*100}%"></div></div><div class="muted">${pct(r.clean_minor/D.overview.net_minor)} / ${pct(r.mixed_minor/D.overview.net_minor)} от общей выручки</div></div>`).join('')||empty('Источники ещё не определены.');}
function showOverview(){let o=D.overview;
 let costs=[['Реклама · записанные расходы',o.ad_minor],['Призы',o.prize_minor],['Время сотрудников',o.staff_minor],['Прочее',o.other_minor]];
 return `<div class="metrics">${card('Выручка после возвратов',money(o.net_minor),`${n(o.orders)} заказов · ${n(o.buyers)} покупателей`)}${card('Выручка clean / mixed',pair(o.clean,o.mixed),'Атрибуция в выбранном окне')}${card('Разница mixed − clean',`<span class="amber">${money(o.delta_minor)}</span>`,'Дополнительно приписано по предположениям')}${card('ROMI clean / mixed',pair(o.romi_clean,o.romi_mixed,pct),'По зарегистрированным затратам')}</div>
 <div class="grid">${panel('Выручка во времени',lineChart(D.daily,[{key:'net_minor',name:'Факт после возвратов',color:'#192c4b'},{key:'clean_minor',name:'Clean',color:'#245bd6'},{key:'mixed_minor',name:'Mixed',color:'#c58c20',dashed:true}],{markers:true})+'<p class="note">Вертикальные метки — размещения и начало акций. При неполном сборе показаны только записанные поступления.</p>')}${panel('Распределение по источникам',sources())}</div>
 <div class="grid equal">${panel('Из чего состоят расходы',table([['Компонент','name'],['Сумма','value',money,true]],costs.map(([name,value])=>({name,value})))+`<p class="note">Скидки ${money(o.discount_minor)} — справочная уступка от обычной цены; уже учтены в цене покупки и повторно не уменьшают ROMI. Денежные затраты: ${money(o.cost_minor)}; записано ${money(o.recorded_cost_minor)}. Котировки размещений отдельно: ${money(o.quoted_ad_minor)}. ${o.discount_unknown?'Неизвестная обычная цена у '+o.discount_unknown+' платежей.':''}</p>`)}${panel('Что требует внимания',D.anomalies.length?table([['День','day',date],['Выручка','net_minor',money,true],['Отклонение','z',x=>df.format(x)+'σ',true]],D.anomalies):'<p class="muted">Необъяснённых отклонений больше 2σ не найдено либо пока недостаточно дней с полным сбором.</p>')+'<p class="note">Аномалия — повод проверить данные и календарь; она сама по себе не объясняет причину изменения.</p>'}</div>
 ${panel('Сделки и основания атрибуции',dealTable(),'<button data-action="csv">Скачать CSV</button>')}
 ${panel('Наблюдаемая LTV : CAC на 90 дней',cohortSummary())}${errorPanel()}`;
}
function dealTable(){return table([['Заказ','order_id',(x,r,i)=>`<button class="button-link" data-deal="${i}">${esc(x)}</button><small>${date(r.ordered_at)}</small>`],['Псевдоним клиента','user_id',esc],['Выручка за период','net_minor',money,true],['Clean','clean',x=>attributionText(x)],['Mixed','mixed',x=>attributionText(x)]],D.deals);}
function attributionText(attrs){return attrs.length?attrs.map(a=>`${esc(D.channels.find(c=>c.channel_id===a.source_channel_id)?.title||a.source_channel_id)} <span class="badge">${pct(a.weight)}</span><small>${esc(basis[a.basis]||a.basis)}</small>`).join('<br>'):'<span class="muted">Без источника</span>';}
function cohortSummary(){let rows=D.cohorts.filter(c=>c.ltv_cac!=null);return rows.length?table([['Когорта','month'],['Источник','source'],['Участников','size',n,true],['LTV : CAC','ltv_cac',x=>df.format(x)+' : 1',true]],rows):'<p class="muted">Нужны созревшие когорты, покупатели, известная стоимость привлечения и полное покрытие оплат. Значение появится после накопления данных.</p>';}
function errorPanel(){let rows=[...D.errors.updates.map(x=>({name:`Telegram · ${x.bot_id}/${x.update_id}`,at:x.received_at,error:x.error})),...D.errors.imports.map(x=>({name:x.filename,at:x.received_at,error:x.error}))];return rows.length?panel('Ошибки, сохранённые для разбора',table([['Источник','name'],['Дата','at',date],['Ошибка','error']],rows)):'';}
function showPlacements(){return `<div class="metrics">${card('Размещений',n(D.placements.length),'Опубликованы в периоде или получили выручку')}${card('Подтверждённых касаний',n(D.placements.reduce((s,r)=>s+r.touches,0)),'За всё наблюдение по этим размещениям')}${card('Известная стоимость',pct(D.quality.known_cost_pct),'Размещения, опубликованные в периоде')}${card('Признак исчерпания',n(D.placements.filter(x=>x.exhausted).length),'NTS < 20% и CER > 60%, без роста аудитории')}</div>`+
 panel('Стоимость и результат',table([['Размещение / источник','id',(x,r)=>`<b>${esc(x)}</b><small>${esc(r.source)}</small><small>${date(r.published_at)} · ${esc(kinds[r.activity_type])}</small>`],['Реклама','ad_minor',money,true],['Скидки / прочее','discount_minor',(x,r)=>money(x)+'<small>'+money(r.extras_minor)+'</small>',true],['Статус стоимости','cost_status',x=>badge({actual:'Факт',recorded_partial:'Частично записано',quote:'Котировка',unknown:'Неизвестно'}[x],x==='unknown'?'warn':'')],['Касания / люди','touches',(x,r)=>n(x)+' / '+n(r.users),true],['Выручка clean / mixed','clean_minor',(x,r)=>pair(x,r.mixed_minor),true],['ROMI clean / mixed','romi_clean',(x,r)=>pair(x,r.romi_mixed,pct),true],['ROMI inc','romi_inc',(x,r)=>x==null?badge('Нет измерения'):pct(x)+'<small>'+esc(r.incrementality_method==='calibration'?'Сценарий с заданной долей прироста':'Импорт результата эксперимента')+'</small>'],['CPA / CPL / CPF','cpa_minor',(x,r)=>`${money(x)}<small>${money(r.cpl_minor)} / ${money(r.cpf_minor)}</small>`,true],['Исчерпание','exhausted',x=>x==null?badge('Недостаточно данных'):badge(x?'Сигнал исчерпания':'Нет сигнала',x?'warn':'ok')]],D.placements))+
 '<p class="note">CPA — стоимость на покупателя с clean-атрибуцией; CPL — на заявку после касания; CPF — на вступившего после касания. Выручка — за выбранный период, стоимость размещения — за всё его наблюдение. Показатели отдельных размещений нельзя суммировать в общий ROMI. Неподтверждённые расходы и оценки помечены.</p>';
}
function showGrowth(){let grouped={};for(let r of D.growth){grouped[r.day]??={day:r.day,joined:0,left:0,net:0};grouped[r.day].joined+=r.joined;grouped[r.day].left-=r.left+r.banned;grouped[r.day].net+=r.net;}let rows=Object.values(grouped).sort((a,b)=>a.day.localeCompare(b.day));
 let joins=rows.reduce((s,r)=>s+r.joined,0),leaves=-rows.reduce((s,r)=>s+r.left,0);
 return `<div class="metrics">${card('Вступления',n(joins),'События, включая повторные вступления')}${card('Выходы и блокировки',n(leaves),'События смены статуса')}${card('Чистый прирост',n(joins-leaves),'Вступления − выходы − блокировки')}${card('Покрытие подписок',D.quality.membership_complete?'Полное':'Не подтверждено','В пределах выбранного периода')}</div>`+
 panel('Приток и отток по дням',lineChart(rows,[{key:'joined',name:'Вступления',color:'#245bd6'},{key:'left',name:'Выходы и блокировки',color:'#c58c20'},{key:'net',name:'Чистый прирост',color:'#10223f'}],{format:n}))+
 panel('Число подписчиков · сохранённые снимки',subscriberChart())+
 '<div class="grid equal">'+panel('По источникам привлечения',table([['Источник','source'],['Вступления','joined',n,true],['Выходы','left',n,true],['Чистый прирост','net',n,true]],Object.values(D.growth.reduce((a,r)=>{let k=r.source;a[k]??={source:r.source,joined:0,left:0,net:0};a[k].joined+=r.joined;a[k].left+=r.left+r.banned;a[k].net+=r.net;return a;},{}))))+
 panel('Наблюдаемые каналы',table([['Канал','title'],['Снимок','observed_at',date],['Подписчиков','subscribers',n,true]],D.channels.filter(c=>c.kind!=='external').map(c=>({...c,...D.snapshots.filter(s=>s.channel_id===c.channel_id).sort((a,b)=>b.observed_at.localeCompare(a.observed_at))[0]}))))+'</div>'+
 panel('Частота и охват рекламных каналов',table([['Источник','source'],['Касания','touches',n,true],['Уникальные люди','users',n,true],['Частота канала','frequency',x=>x==null?'—':df.format(x),true],['Аудитория источника','audience',n,true],['CER','cer',pct,true]],D.source_metrics))+
 panel('Повторные размещения и запас аудитории',table([['Источник / размещение','id',(x,r)=>esc(r.source)+'<small>'+esc(x)+'</small>'],['NTS · новые / все','nts',pct,true],['CER · охват аудитории','cer',pct,true],['Частота касаний','frequency',x=>df.format(x||0),true],['Статус','exhausted',x=>x==null?badge('Нужны снимки аудитории'):badge(x?'Есть сигнал исчерпания':'Нет сигнала',x?'warn':'ok')]],D.placements))+
 '<p class="note">NTS: новые люди / все люди размещения. CER: накопленные уникальные люди источника / последний известный размер его аудитории. Частота канала: все его касания / уникальные люди канала; в таблице размещений — частота конкретного размещения. Уникальность ограничена наблюдаемой историей; пересланные ссылки не доказывают членство в рекламном канале.</p>';
}

function subscriberChart(){let channels=D.channels.filter(c=>c.kind!=='external'),byDay={};for(let s of D.snapshots){if(!channels.some(c=>c.channel_id===s.channel_id)||s.observed_at<D.start)continue;let day=s.observed_at.slice(0,10);byDay[day]??={day};byDay[day][s.channel_id]=s.subscribers;}return lineChart(Object.values(byDay).sort((a,b)=>a.day.localeCompare(b.day)),channels.map((c,i)=>({key:c.channel_id,name:c.title,color:['#245bd6','#c58c20','#30556a'][i%3]})),{format:n});}

function curveChart(curve,field='conversion'){return lineChart(curve,[{key:'clean_'+field,name:'Clean',color:'#245bd6'},{key:'mixed_'+field,name:'Mixed',color:'#c58c20',dashed:true}],{format:field==='conversion'?pct:money,height:200});}
function showEvents(){if(!D.events.length)return empty('Завершённых активностей пока нет. Добавьте календарь акций и мероприятий.');
 return `<p class="muted">История завершений до ${date(D.end)}. Выручка относится к участникам активности и не доказывает её причинный эффект.</p><div class="events">`+D.events.map(e=>{
 let c7=e.curve[0],c90=e.curve[3];return `<article class="panel"><div class="event-title"><div><h2>${esc(e.title)}</h2><span class="muted">${date(e.starts_at)} — ${date(e.ends_at)}</span></div>${badge(kinds[e.kind]||e.kind)}</div><div class="event-measures"><div><small>💰 Выручка за 7 дней</small><strong>${pair(c7.clean_revenue_minor,c7.mixed_revenue_minor)}</strong><small>clean / mixed · ${c7.mature}/${c7.total} созрели</small></div><div><small>🌱 Выручка на 8–90-й день</small><strong>${money(e.awakened_minor)}</strong><small>Одинаковая зрелая группа: ${n(e.awakened_mature)}</small></div><div><small>👥 Аудитория</small><strong>${n(e.audience)}</strong><small>Уникальные наблюдаемые люди</small></div></div><p>ROMI 90д clean / mixed: ${pair(c90.romi_clean,c90.romi_mixed,pct)}</p><details><summary>Расходы, конверсия и воронка</summary><p class="note">Реклама ${money(e.ad_minor)} · скидки справочно ${money(e.discount_minor)} · призы ${money(e.prize_minor)} · сотрудники ${money(e.staff_minor)}. Денежные затраты ${money(e.cost_minor)}.</p>${curveChart(e.curve)}${table([['Горизонт','day',x=>x+' дней'],['Созрели / всего','mature',(x,r)=>x+' / '+r.total],['Покупки clean / mixed','clean_buyers',(x,r)=>n(x)+' / '+n(r.mixed_buyers)],['Конверсия','clean_conversion',(x,r)=>pair(x,r.mixed_conversion,pct)],['Выручка clean / mixed','clean_revenue_minor',(x,r)=>pair(x,r.mixed_revenue_minor)],['ROMI','romi_clean',(x,r)=>pair(x,r.romi_mixed,pct)]],e.curve)}${e.kind==='hackathon'?`<h3 style="margin-top:20px">Воронка мероприятия</h3><p>Зарегистрировались <b>${e.registered}</b> → сдали работу <b>${e.active}</b> → завершили <b>${e.completed}</b> → подписаны через 30д <b>${n(e.retained30)}</b> → купили после этого <b>${e.retained_buyers}</b></p><p class="note">Покупателей за 90 дней после регистрации независимо от удержания: ${e.buyers}. Удержание: подтверждено ${e.retention_observed} из ${e.retention_eligible} допустимых наблюдений. Наличие работы определяет активное участие; завершение подтверждает организатор.</p><p>Стоимость: регистрация ${money(e.cost_registered)} · активный ${money(e.cost_active)} · завершивший ${money(e.cost_completed)} · покупатель ${money(e.cost_buyer)}.</p>`:`<p class="note">CPL (после касания): ${money(e.cpl_minor)} · ${n(e.leads)} заявок. Стоимость на наблюдаемого участника: ${money(e.audience&&e.cost_minor!=null?e.cost_minor/e.audience:null)}. Выручка на 8–90-й день с подтверждённой связью с последующей акцией: ${money(e.promoted_awakened_minor)}. ROMI inc: нет измерения. Суммы разных активностей могут пересекаться по одним людям; их нельзя складывать.</p>`}</details></article>`;
 }).join('')+'</div>';
}
function showFunnel(){let f=D.funnel[mode],labels=['Касание','Заявка','Заказ','Оплата'];return `<div class="tools"><label>Основание<select id="funnel-mode"><option value="clean"${mode==='clean'?' selected':''}>Clean</option><option value="mixed"${mode==='mixed'?' selected':''}>Mixed · включая ответы</option></select></label><span class="muted">Пользователи с первым подходящим касанием в периоде</span></div>`+panel('Последовательная воронка',`<div class="funnel">${labels.map((x,i)=>`<div class="funnel-step"><span>${x}</span><strong>${n(f.counts[i])}</strong><span>${i?pct(f.counts[i-1]?f.counts[i]/f.counts[i-1]:null)+' от прошлого шага':'100% группы'}</span></div>`).join('')}</div><p class="note">У каждого человека заявка следует за касанием, заказ — за заявкой, оплата — за заказом. Покупки без заявки сюда не входят; они видны в реестре сделок. Календарные предположения не создают выдуманное касание.</p>`)+
 panel('По типу источника',table([['Тип','type',x=>esc(kinds[x]||x)],...labels.map((x,i)=>[x,'counts',v=>n(v[i]),true])],f.by_type))+
 panel('Сравнение clean / mixed',table([['Шаг','name'],['Clean','clean',n,true],['Mixed','mixed',n,true]],labels.map((name,i)=>({name,clean:D.funnel.clean.counts[i],mixed:D.funnel.mixed.counts[i]}))));}
function showForecast(){if(!D.forecasts.length)return empty('Сохранённых прогнозов пока нет. После 35 полных дней сбора оплат можно рассчитать baseline; прогноз ML-модели добавляется отдельной загрузкой.');
 let origins=[...new Set(D.forecasts.map(x=>x.origin_at))];let selected=window.forecastOrigin&&origins.includes(window.forecastOrigin)?window.forecastOrigin:origins[0];window.forecastOrigin=selected;
 let runs=D.forecasts.filter(r=>r.origin_at===selected),rows={};for(let r of runs)for(let p of r.points){rows[p.day]??={day:p.day,actual_minor:p.actual_minor};rows[p.day][r.model]=p.value_minor;if(r.model==='seasonal_naive'){rows[p.day].lower=p.lower_minor;rows[p.day].upper=p.upper_minor;}}
 let series=[{key:'actual_minor',name:'Факт',color:'#13233e'},...runs.map((r,i)=>({key:r.model,name:{naive:'Наивный',seasonal_naive:'Сезонный наивный'}[r.model]||r.model,color:['#c58c20','#245bd6','#8b55be'][i%3],dashed:true}))];
 let campaigns=runs[0].known_campaigns;
 return `<div class="tools"><label>Дата расчётного среза<select id="forecast-origin">${origins.map(x=>`<option value="${esc(x)}"${x===selected?' selected':''}>${date(x)} ${x.slice(11,16)} UTC</option>`).join('')}</select></label><span class="muted">Интервал по ошибкам ретропрогнозов; номинальные 80%, покрытие не гарантировано.</span></div>`+
 panel('Факт и сохранённый прогноз',lineChart(Object.values(rows).sort((a,b)=>a.day.localeCompare(b.day)),series,{band:['lower','upper']}))+
 panel('Сравнение на прошлых датах',table([['Метод','model',x=>esc({naive:'Наивный · последнее значение',seasonal_naive:'Сезонный наивный · тот же день недели'}[x]||x)],['MAE','backtest_mae_minor',money,true],['WAPE','backtest_wape',pct,true],['Проверенных точек','backtest_n',n,true],['Обучающие данные до','training_end_at',date],['Сохранён','created_at',date]],runs))+
 '<p class="note">MAE — средняя абсолютная ошибка в рублях. WAPE — сумма абсолютных ошибок / сумма абсолютных фактов. Если архив импортирован позже, он не считается известным для старых срезов. Здесь показаны простые временные baseline; обученные модели покупки и рекламы находятся в отдельном разделе «ML-сценарии».</p>'+
 panel('Кампании, известные на дату прогноза',table([['Кампания','id'],['Тип','kind'],['Начало','starts_at',date],['Стала известна','known_at',date]],campaigns))+
 '<p class="note">Baseline не использует кампании как признаки. Список фиксирует доступную информацию для будущей модели и проверки known_at.</p>';
}
function showCohorts(){let rows=D.cohorts;return `<p class="muted">Когорты по месяцу первого наблюдения, источнику, типу и уверенности. Точные границы входа — в реестре. На каждом горизонте учитываются созревшие пользователи; состав групп может различаться.</p>`+
 panel('Реестр когорт',table([['Месяц / даты входа','month',(x,r)=>`<b>${esc(x)}</b><small>${date(r.entry_min)} — ${date(r.entry_max)}</small>`],['Источник','source'],['Тип / уверенность','activity_type',(x,r)=>esc(kinds[x]||x)+'<small>'+esc(r.confidence)+'</small>'],['Людей','size',n,true],['Конверсия 30д clean / mixed','curve',x=>pair(x[1].clean_conversion,x[1].mixed_conversion,pct),true],['LTV : CAC · 90д','ltv_cac',x=>x==null||!Number.isFinite(x)?'—':df.format(x)+' : 1',true],['Статус','status',x=>badge(x,x==='горизонт закрыт'?'ok':'warn')],['Кривая','month',(_,r,i)=>`<button class="button-link" data-cohort="${i}">7 / 30 / 60 / 90</button>`]],rows))+
 '<p class="note">«Горизонт закрыт» означает, что прошло 90 дней; полнота сбора дополнительно проверяется для каждой метрики. Пропуски отображаются как «—», а не как нулевая конверсия.</p>';
}
function mlInput(label,key,type='number',extra=''){return `<label>${label}<input id="ml-${key}" type="${type}" value="${esc(mlForm[key])}" ${extra}></label>`;}
function modelQuality(q){return q==='baseline_is_better_on_test'?'Baseline лучше на тесте':q==='better_than_baseline_on_test'?'Лучше baseline на тесте':q||'Не определено';}
function modelTable(){const names={purchase:'Вероятность покупки',new_users:'Новые пользователи',new_buyers:'Новые покупатели'};return table([['Задача','task',x=>esc(names[x]||x)],['Выбранная модель','model'],['Log loss / MAE','metric',x=>Number.isFinite(x)?new Intl.NumberFormat('ru-RU',{maximumFractionDigits:4}).format(x):'—',true],['Проверка качества','quality',x=>badge(modelQuality(x),x==='baseline_is_better_on_test'?'warn':'')]],Object.entries(M.models||{}).map(([task,r])=>({task,model:r.winner?.model||'См. отчёт',metric:r.test_metrics?.logloss??r.test_metrics?.mae,quality:r.quality_status})));}
function extrapolationNote(r){let ex=r.extrapolation||{};let count=Object.keys(ex.numeric_outside_training_range||{}).length+Object.keys(ex.unseen_categories||{}).length;return `<p class="note">${count?'Есть признаки вне обучающего диапазона: '+count+'. Это экстраполяция; перенос прогноза требует проверки.':'Проверка диапазонов признаков не выявила экстраполяции.'} ${r.plan_seen_in_training===false?'Такой план не встречался в обучении.':''}</p>`;}
function customerCards(){let r=customerResult;if(!r)return empty('Задайте условия и рассчитайте сценарий для всей доступной аудитории.');return `<div class="metrics">${card('Подходят под расчёт',n(r.eligible_users),'Пользователи без оплаченного курса')}${card('Ожидаемые покупатели · сейчас',df.format(r.expected_buyers_current),'Сумма вероятностей, горизонт '+n(r.horizon_days)+' дней')}${card('Ожидаемые покупатели · сценарий',df.format(r.expected_buyers_scenario),'Условная оценка модели')}${card('Разница сценариев',df.format(r.difference_buyers),'Не доказанный прирост от воздействия')}</div>`+table([['Показатель','name'],['Текущие условия','current',money,true],['Заданный сценарий','scenario',money,true]],[{name:'Оценка выручки',current:r.expected_revenue_current_uniform_timing_minor,scenario:r.expected_revenue_scenario_uniform_timing_minor},{name:'Вклад до расходов кампании',current:r.contribution_current_minor,scenario:r.contribution_scenario_before_campaign_cost_minor}])+extrapolationNote(r)+`<p class="note">Статус качества модели: ${esc(modelQuality(r.quality_status))}. Цена покупки распределяется по горизонту равномерно. Уже оплаченный и невозвращённый курс исключён. Индивидуальные идентификаторы через API не выдаются.</p>`;}
function channelCards(){let r=channelResult;if(!r)return empty('Выберите ранее использованный канал и рассчитайте условный предел цены.');return `<div class="metrics">${card('Новые пользователи',df.format(r.new_users),'Ожидаются за '+n(r.arrival_days)+' дней')}${card('Новые покупатели',df.format(r.new_buyers),'Ожидаются за '+n(r.buyer_days)+' дней')}${card('Предел цены · при 100% прироста',money(r.attributed_price_ceiling_minor),'Только сценарий полной инкрементальности')}${card('Предел с заданной долей прироста',money(r.maximum_price_minor),r.assumed_incrementality==null?'Доля прироста не задана':pct(r.assumed_incrementality)+' дополнительных покупок — допущение')}</div><p class="note">Это потолок экономически допустимой цены при заданной марже и ROI, а не предсказание прайса владельца. ${r.meets_assumed_roi==null?'Для сравнения нужны запрошенная цена и доля прироста.':r.meets_assumed_roi?'Цена проходит заданный сценарный ROI.':'Цена выше допустимой при заданных допущениях.'} Исторических размещений: ${n(r.history?.past_placements)}. Ошибка прогноза покупателей: ${r.buyers_empirical_error_band?.map(x=>df.format(x)).join(' — ')||'не оценена'} (эмпирический диапазон, не гарантия).</p>`+extrapolationNote(r);}
function showML(){
 const status=badge('Реализовано частично','warn');
 let top=`<div class="ml-heading"><p class="eyebrow">Отдельная ML-составляющая · та же выбранная SQLite-база</p>${status}</div><div class="knowledge-grid"><div><b>Что мы знаем</b><p>Записанные события и оплаты доступны в операционных вкладках.</p></div><div><b>Что мы оцениваем</b><p>Вероятности покупки, отклик канала и экономический потолок цены.</p></div><div><b>Что пока узнать нельзя</b><p>Причинный прирост от акции без контрольной группы и журнала назначений.</p></div></div>`;
 if(!M)return top+empty('Проверяем доступность ML-моделей…');
 top+=`<div class="notice">${esc(M.reason||M.note||'Модуль сценарного анализа')}. ${M.provenance==='synthetic'?'Обучение и результаты — синтетическое демо. Качество на клиентах Поступашек не установлено.':''}</div>`;
 if(!M.available)return top+panel('Что нужно для запуска','<p>Подключите ML-таблицы, установите зависимости и обучите модели отдельной командой из <code>ml/README.md</code>. Операционные разделы продолжают работать без ML.</p>');
 let disabled=mlBusy||window.SNAPSHOT?'disabled':'';
 return top+panel('Условия расчёта',`<div class="scenario-fields">${mlInput('Курс','course_id','text','required')}${mlInput('Дата среза UTC','as_of','date','required')}${mlInput('Скидка, %','discount_pct','number','min="0" max="100"')}${mlInput('Длительность скидки, дней','discount_days','number','min="0" max="14"')}${mlInput('Плановых сообщений','contacts','number','min="0" max="4"')}</div><p class="note">Это отдельный прогноз на дату среза; фильтры атрибуции и периода выше относятся к операционным вкладкам. Плановые сообщения равномерно распределены по 14 дням. Факт их прочтения не предполагается. Комиссии, возвраты и расходы кампании в форме равны нулю; для своей экономики используйте CLI.</p>`)+
 panel('1. Клиенты: текущие условия и сценарий',`<div class="tools"><button class="primary" data-action="ml-customers" ${disabled}>${mlBusy?'Расчёт…':'Рассчитать аудиторию'}</button><span class="muted">${window.SNAPSHOT?'Снимок: для расчёта откройте локальное приложение.':'Пакетный расчёт без изменения фактов.'}</span></div>${customerCards()}`)+
 panel('2. Реклама: допустимая цена повторного размещения',`<div class="scenario-fields"><label>Канал<select id="ml-channel_id">${(M.channels||[]).map(c=>`<option value="${esc(c.channel_id)}"${c.channel_id===mlForm.channel_id?' selected':''}>${esc(c.title)}</option>`).join('')}</select></label>${mlInput('Доля дополнительных покупок, %','incrementality','number','min="0" max="100" placeholder="Неизвестна"')}${mlInput('Целевой ROI, %','required_roi','number','min="0"')}${mlInput('Запрошенная цена, ₽','quoted_price','number','min="0" placeholder="Не задана"')}${mlInput('Будущие просмотры','expected_views','number','min="0" placeholder="Из последнего снимка"')}</div><div class="tools"><button class="primary" data-action="ml-channels" ${disabled}>Рассчитать предел цены</button></div>${channelCards()}`)+
 (mlError?`<div class="notice" role="alert">${esc(mlError)}</div>`:'')+panel('Модели и честная проверка качества',modelTable()+'<p class="note">Выбор параметров выполняется по времени на validation; финальный тест не участвует в подборе. Ни одна метрика на синтетике не подтверждает бизнес-эффективность. Временной прогноз выручки в операционных вкладках — отдельный baseline.</p>');
}
function readMLForm(){for(const key of Object.keys(mlForm)){let e=$('ml-'+key);if(e)mlForm[key]=e.value;}}
async function loadML(){if(window.SNAPSHOT){M=SNAPSHOT.ml||{available:false,reason:'ML-результаты не включены в этот снимок'};mlForm.course_id=M.course_id||'';mlForm.as_of=(M.as_of||meta.end||'').slice(0,10);mlForm.channel_id=M.channels?.[0]?.channel_id||'';render();return;}try{const r=await fetch('/api/ml/status');M=await r.json();if(!r.ok)throw Error(M.error);if(!mlForm.course_id)mlForm.course_id=M.course_id||'';if(!mlForm.as_of)mlForm.as_of=(M.as_of||meta.end||'').slice(0,10);if(!mlForm.channel_id)mlForm.channel_id=M.channels?.[0]?.channel_id||'';}catch(e){M={available:false,reason:e.message};}if(tab==='ml')render();}
async function runML(kind){if(mlBusy||window.SNAPSHOT)return;readMLForm();const form=mlForm;let count=Number(form.contacts),plan={discount_pct:Number(form.discount_pct),discount_days:Number(form.discount_days),contacts:Array.from({length:Math.max(0,Math.min(4,count))},(_,i)=>({kind:'message',day:Math.floor(i*14/Math.max(count,1))}))};let payload={course_id:form.course_id,as_of:form.as_of,plan,required_roi:Number(form.required_roi)/100};if(kind==='channels'){payload.channel_id=form.channel_id;payload.incrementality=form.incrementality===''?null:Number(form.incrementality)/100;payload.quoted_price_minor=form.quoted_price===''?null:Math.round(Number(form.quoted_price)*100);payload.expected_views=form.expected_views===''?null:Number(form.expected_views);}mlBusy=true;mlError='';render();try{let r=await fetch('/api/ml/'+kind,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':meta.csrf},body:JSON.stringify(payload)});let v=await r.json();if(!r.ok)throw Error(v.error);if(kind==='customers')customerResult=v;else channelResult=v;}catch(e){mlError=e.message;}finally{mlBusy=false;render();}}
function render(){if(!D)return;quality();$('filters').hidden=tab==='ml';$('quality').hidden=tab==='ml';$('upload').hidden=tab==='ml';let t=tabs.find(x=>x[0]===tab);$('title').textContent=t[2];$('breadcrumb').textContent=t[1];document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x.dataset.tab===tab);x.setAttribute('aria-current',x.dataset.tab===tab?'page':'false');});
 $('content').innerHTML=({overview:showOverview,placements:showPlacements,growth:showGrowth,events:showEvents,funnel:showFunnel,forecast:showForecast,cohorts:showCohorts,ml:showML}[tab])();
 $('provenance').hidden=false;$('provenance').textContent=(D.provenance==='synthetic'?'СИНТЕТИЧЕСКОЕ ДЕМО · Все люди, оплаты и показатели вымышлены. ':'ИСТОЧНИК ДАННЫХ ТРЕБУЕТ ПРОВЕРКИ · Отображаются записанные значения; полнота и качество оцениваются отдельно. ')+(window.SNAPSHOT?'Автономный снимок. Переключение вкладок и детализация доступны; свежие данные и фильтры — в приложении.':'');
}
async function refresh(){if(busy||window.SNAPSHOT)return;busy=true;$('refresh').disabled=true;$('error').hidden=true;try{let p=new URLSearchParams({start:$('start').value,end:$('end').value,method:$('method').value,lookback:$('lookback').value});let r=await fetch('/api/report?'+p);let v=await r.json();if(!r.ok)throw Error(v.error);D=v;render();$('updated').textContent='Обновлено '+new Date().toLocaleTimeString('ru-RU')+' · каждые 30 с';}catch(e){$('error').textContent=e.message;$('error').hidden=false;}finally{busy=false;$('refresh').disabled=false;}}
function showDeal(i){let r=D.deals[i];$('dialog-title').textContent='Заказ '+r.order_id;$('dialog-body').innerHTML=`<div class="metrics">${card('Сумма заказа',money(r.total_minor))}${card('Выручка в периоде',money(r.net_minor))}${card('Псевдоним клиента',esc(r.user_id))}${card('Дата заказа',date(r.ordered_at))}</div><p>Clean: ${attributionText(r.clean)}</p><p>Mixed: ${attributionText(r.mixed)}</p><h3>Оплаты и возвраты</h3>${table([['ID','payment_id'],['Дата','occurred_at',date],['Тип','kind',x=>x==='payment'?'Оплата':'Возврат'],['Сумма','net_minor',money,true]],r.payments)}<h3 style="margin-top:20px">История касаний</h3>${table([['Дата','occurred_at',date],['Событие','kind',x=>esc(basis[x]||x)],['Размещение','placement_id'],['Уверенность','confidence'],['До заказа и в окне','eligible',x=>badge(x?'Да':'Нет',x?'ok':'')]],r.touches)}<p class="note">Заявки: ${esc(r.lead_ids.join(', ')||'нет')}. Отписки и служебные действия не участвуют в атрибуции.</p>`;$('detail').showModal();}
function showCohort(i){let c=D.cohorts[i];$('dialog-title').textContent=c.source+' · '+c.month;$('dialog-body').innerHTML=curveChart(c.curve)+table([['Горизонт','day',x=>x+' дней'],['Созревших','mature',n,true],['Покрытие clean','clean_observed',(x,r)=>x+' / '+r.clean_eligible],['Конверсия clean / mixed','clean_conversion',(x,r)=>pair(x,r.mixed_conversion,pct)],['Накопленная выручка clean / mixed','clean_revenue_minor',(x,r)=>pair(x,r.mixed_revenue_minor)],['LTV clean / mixed','clean_ltv_minor',(x,r)=>pair(x,r.mixed_ltv_minor)]],c.curve)+`<p class="note">LTV — наблюдаемая выручка на покупателя за горизонт. CAC — распределённые расходы привлечения на покупателя, для полностью созревшей когорты. Дата первого входа закрепляется по самому раннему наблюдению. Unknown не заменяется последующим известным источником.</p>`;$('detail').showModal();}
function csv(){const rows=[['order_id','user_id','ordered_at','net_rub','clean_sources','mixed_sources'],...D.deals.map(r=>[r.order_id,r.user_id,r.ordered_at,r.net_minor/100,r.clean.map(a=>a.source_channel_id+':'+a.weight).join('|'),r.mixed.map(a=>a.source_channel_id+':'+a.weight).join('|')])];let text='\uFEFF'+rows.map(r=>r.map(x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n');let url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));let a=document.createElement('a');a.href=url;a.download='postupashki_deals.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('nav').innerHTML='<div class="nav-group">Операционная аналитика</div>'+tabs.map((x,i)=>(i===7?'<div class="nav-group">Модели и сценарии</div>':'')+`<button data-tab="${x[0]}"><span class="num">0${i+1}</span>${x[1]}</button>`).join('');
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.tab){if(tab==='ml')readMLForm();tab=b.dataset.tab;render();if(tab==='ml')loadML();}if(b.dataset.deal!==undefined)showDeal(+b.dataset.deal);if(b.dataset.cohort!==undefined)showCohort(+b.dataset.cohort);if(b.dataset.action==='csv')csv();if(b.dataset.action==='ml-customers')runML('customers');if(b.dataset.action==='ml-channels')runML('channels');});
document.addEventListener('change',e=>{if(e.target.id.startsWith('ml-'))readMLForm();if(e.target.id==='funnel-mode'){mode=e.target.value;render();}if(e.target.id==='forecast-origin'){window.forecastOrigin=e.target.value;render();}});
$('filters').addEventListener('change',refresh);$('filters').addEventListener('submit',e=>{e.preventDefault();refresh();});$('refresh').onclick=refresh;$('close-dialog').onclick=()=>$('detail').close();$('upload').onclick=()=>$('import-dialog').showModal();$('close-import').onclick=()=>$('import-dialog').close();
$('import-submit').onclick=async()=>{let file=$('file').files[0];if(!file){$('import-result').textContent='Выберите файл.';return;}try{let payload=JSON.parse(await file.text());$('import-submit').disabled=true;let r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':meta.csrf},body:JSON.stringify(payload)});let v=await r.json();if(!r.ok)throw Error(v.error);$('import-result').textContent=`Добавлено: ${v.inserted}. Идентичных повторов: ${v.duplicates}. Дашборд обновлён.`;await refresh();}catch(e){$('import-result').textContent='Не загружено: '+e.message;}finally{$('import-submit').disabled=false;}};
(async()=>{try{if(window.SNAPSHOT){D=SNAPSHOT.report;meta=SNAPSHOT.meta;}else{let r=await fetch('/api/meta');meta=await r.json();if(!r.ok)throw Error(meta.error);}$('start').value=meta.start;$('end').value=meta.end;if(window.SNAPSHOT){$('start').value=D.start.slice(0,10);$('end').value=new Date(new Date(D.end).getTime()-86400000).toISOString().slice(0,10);for(let id of ['start','end','method','lookback','refresh','upload'])$(id).disabled=true;$('updated').textContent='Снимок на '+date(D.knowledge_at);render();}else{await refresh();setInterval(()=>{if(!document.hidden)refresh();},30000);}}catch(e){$('error').hidden=false;$('error').textContent=e.message;$('content').innerHTML=empty('Не удалось прочитать базу.');}})();
